version: "3.8"

services:
  # app:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   container_name: nest_app
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./api:/usr/src/app
  #   ports:
  #     - "3000:3000"
  #   command: npm run start
  #   depends_on:
  #     - db
  #     - redis

  # worker:
  #   build:
  #     context: ./worker
  #     dockerfile: Dockerfile
  #   container_name: nest_worker
  #   working_dir: /usr/src/worker
  #   volumes:
  #     - ./worker:/usr/src/worker
  #   ports:
  #     - "3001:3001"
  #   command: npm run start
  #   depends_on:
  #     - db
  #     - redis

  db:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_db
    ports:
      - "6379:6379"

volumes:
  db_data:
